import { VerifiedEvent } from './types'

const now = Date.now()
const m = (min: number) => new Date(now - min * 60000).toISOString()

export const MOCK_EVENTS: VerifiedEvent[] = [
  {
    id: 'mock-001',
    createdAt: m(4),
    headline: 'IDF intercepts ballistic missile over Red Sea',
    summary: 'Israeli Arrow-3 defense system successfully intercepted a ballistic missile launched from Yemen over the Red Sea. No injuries or infrastructure damage reported. The IDF confirmed the interception via official statement.',
    locationName: 'Red Sea, off Eilat',
    latitude: 29.5, longitude: 34.9,
    country: 'Israel', region: 'Middle East',
    severity: 'CRITICAL', severityColor: 'RED', category: 'STRIKE',
    sources: [
      { handle: '@sentdefender',  tier: 3, url: 'https://x.com/sentdefender', quote: 'Arrow-3 activation confirmed, missile launch from Yemen detected' },
      { handle: '@ELINTNews',     tier: 3, url: 'https://x.com/ELINTNews',    quote: 'Ballistic missile trajectory plotted, Red Sea vector toward Eilat' },
      { handle: '@TimesofIsrael', tier: 2, url: 'https://www.timesofisrael.com', quote: 'IDF confirms successful interception of ballistic missile over Red Sea' },
    ],
    confidenceScore: 88, status: 'VERIFIED',
    tags: ['IDF', 'Arrow-3', 'Houthi', 'missile', 'Red Sea', 'Eilat'],
    perspective: {
      sideA: 'Houthi military spokesperson claims responsibility, calling it response to Gaza operations',
      sideB: 'IDF confirms Arrow-3 successful interception with zero damage to Israeli territory',
      neutral: 'Missile trajectory independently confirmed by ELINT monitors; no casualties reported',
    },
  },
  {
    id: 'mock-002',
    createdAt: m(11),
    headline: 'IRGC conducts live-fire naval exercise in Strait of Hormuz',
    summary: 'Iran\'s Islamic Revolutionary Guard Corps Navy conducted live-fire exercises in the Strait of Hormuz involving fast-attack boats and coastal missile systems. US Fifth Fleet monitoring the situation from international waters.',
    locationName: 'Strait of Hormuz, Iran',
    latitude: 26.6, longitude: 56.2,
    country: 'Iran', region: 'Middle East',
    severity: 'HIGH', severityColor: 'ORANGE', category: 'MOVEMENT',
    sources: [
      { handle: '@AuroraIntel',   tier: 3, url: 'https://x.com/AuroraIntel',  quote: 'IRGCN fast boats active in Hormuz, coastal batteries elevated' },
      { handle: '@IranIntl',      tier: 2, url: 'https://www.iranintl.com',   quote: 'IRGC Naval exercise announced via state media, includes missile drill' },
      { handle: '@DefenseOne',    tier: 2, url: 'https://www.defenseone.com', quote: 'US Fifth Fleet statement: monitoring IRGC activities in Hormuz region' },
    ],
    confidenceScore: 81, status: 'VERIFIED',
    tags: ['IRGC', 'Iran', 'Hormuz', 'naval', 'exercise', 'US Navy'],
    perspective: {
      sideA: 'Iran state media frames exercise as defensive capability demonstration',
      sideB: 'US Fifth Fleet states freedom of navigation will be maintained',
      neutral: 'Exercise confirmed by satellite imagery and multiple independent maritime trackers',
    },
  },
  {
    id: 'mock-003',
    createdAt: m(23),
    headline: 'Hezbollah launches 35 rockets at northern Israel communities',
    summary: 'Hezbollah fired approximately 35 Katyusha rockets targeting communities in northern Israel, including Kiryat Shmona and Metula. Iron Dome intercepted majority; several rockets landed in open areas. No fatalities reported.',
    locationName: 'Kiryat Shmona, Israel',
    latitude: 33.2, longitude: 35.6,
    country: 'Israel', region: 'Middle East',
    severity: 'HIGH', severityColor: 'ORANGE', category: 'STRIKE',
    sources: [
      { handle: '@clashreport',    tier: 3, url: 'https://x.com/clashreport',  quote: 'Rocket barrage from Lebanon, ~35 projectiles, Iron Dome active' },
      { handle: '@sentdefender',   tier: 3, url: 'https://x.com/sentdefender', quote: 'Multiple interceptions over Galilee, sirens in Kiryat Shmona and Metula' },
      { handle: '@TimesofIsrael',  tier: 2, url: 'https://www.timesofisrael.com', quote: 'Hezbollah claims responsibility for rocket fire at northern Israel' },
      { handle: '@BBCWorld',       tier: 1, url: 'https://www.bbc.com',         quote: 'Dozens of rockets fired from Lebanon at northern Israeli towns' },
    ],
    confidenceScore: 95, status: 'VERIFIED',
    tags: ['Hezbollah', 'rocket', 'Israel', 'Iron Dome', 'Lebanon', 'Katyusha'],
    perspective: {
      sideA: 'Hezbollah states attack in response to IDF airstrikes in southern Lebanon',
      sideB: 'IDF confirms Iron Dome activated; responding with artillery fire on launch sites',
      neutral: 'BBC and Times of Israel independently confirmed barrage; no fatalities per emergency services',
    },
  },
  {
    id: 'mock-004',
    createdAt: m(38),
    headline: 'US deploys additional carrier strike group to Eastern Mediterranean',
    summary: 'The USS Gerald R. Ford carrier strike group is repositioning to the Eastern Mediterranean following escalating tensions. The deployment includes guided-missile destroyers and F/A-18 squadrons, according to Pentagon sources.',
    locationName: 'Eastern Mediterranean',
    latitude: 34.5, longitude: 30.0,
    country: 'International Waters', region: 'Middle East',
    severity: 'HIGH', severityColor: 'ORANGE', category: 'MOVEMENT',
    sources: [
      { handle: '@IntelSky',      tier: 3, url: 'https://x.com/IntelSky',    quote: 'USS Gerald R. Ford group position updated, heading Eastern Med' },
      { handle: '@DefenseOne',    tier: 2, url: 'https://www.defenseone.com', quote: 'Pentagon confirms carrier group repositioning, officials cite regional tensions' },
      { handle: '@Reuters',       tier: 1, url: 'https://www.reuters.com',    quote: 'US deploys additional warships to Mediterranean amid Middle East tensions' },
    ],
    confidenceScore: 92, status: 'VERIFIED',
    tags: ['US Navy', 'carrier', 'Mediterranean', 'Pentagon', 'escalation'],
    perspective: {
      sideA: 'Iran state media calls deployment "provocative and destabilizing"',
      sideB: 'Pentagon: deployment is precautionary and reaffirms US commitment to regional stability',
      neutral: 'Carrier group position independently confirmed by vessel tracking services (MarineTraffic)',
    },
  },
  {
    id: 'mock-005',
    createdAt: m(52),
    headline: 'Iranian parliament votes to suspend IAEA inspections access',
    summary: 'Iranian parliament passed a bill to suspend enhanced IAEA monitoring access to nuclear sites, in response to a European resolution criticizing Iran\'s nuclear program. The bill now requires Guardian Council approval.',
    locationName: 'Tehran, Iran',
    latitude: 35.7, longitude: 51.4,
    country: 'Iran', region: 'Middle East',
    severity: 'HIGH', severityColor: 'ORANGE', category: 'DIPLOMATIC',
    sources: [
      { handle: '@IranIntl',       tier: 2, url: 'https://www.iranintl.com',   quote: 'Majles approves bill to halt IAEA additional protocol, 163 votes in favor' },
      { handle: '@ianbremmer',     tier: 2, url: 'https://x.com/ianbremmer',   quote: 'Iran parliament vote on IAEA access: major escalation in nuclear standoff' },
      { handle: '@AJEnglish',      tier: 1, url: 'https://www.aljazeera.com',  quote: 'Iran lawmakers vote to restrict UN nuclear inspectors amid tensions' },
      { handle: '@Guardian',       tier: 1, url: 'https://www.theguardian.com',quote: 'Iran MPs vote to end IAEA additional monitoring in blow to nuclear deal' },
    ],
    confidenceScore: 97, status: 'VERIFIED',
    tags: ['Iran', 'IAEA', 'nuclear', 'Majles', 'JCPOA', 'diplomacy'],
    perspective: {
      sideA: 'Iran Foreign Ministry: vote is legitimate response to European "political pressure"',
      sideB: 'EU and US call vote "deeply counterproductive" and a threat to nonproliferation',
      neutral: 'IAEA confirms it has received unofficial notification; formal position pending',
    },
  },
  {
    id: 'mock-006',
    createdAt: m(74),
    headline: 'Houthi anti-ship missile targets oil tanker in Gulf of Aden',
    summary: 'A Houthi anti-ship missile reportedly struck a Liberian-flagged oil tanker in the Gulf of Aden. The vessel sustained damage to the hull; crew reported safe and evacuated. Maritime security organizations have issued warnings to shipping.',
    locationName: 'Gulf of Aden',
    latitude: 12.5, longitude: 46.8,
    country: 'Yemen', region: 'Middle East',
    severity: 'CRITICAL', severityColor: 'RED', category: 'STRIKE',
    sources: [
      { handle: '@OSINTWarfare',   tier: 3, url: 'https://x.com/OSINTWarfare', quote: 'Oil tanker hit in Gulf of Aden, Houthi ASM reported' },
      { handle: '@Conflict_Radar', tier: 3, url: 'https://x.com/Conflict_Radar', quote: 'Ambrey confirms tanker struck, crew evacuated safely' },
      { handle: '@WarMonitors',    tier: 3, url: 'https://x.com/WarMonitors',  quote: 'UKMTO Alert: vessel struck by projectile in Gulf of Aden, crew safe' },
      { handle: '@Reuters',        tier: 1, url: 'https://www.reuters.com',    quote: 'Houthi missile hits oil tanker in Gulf of Aden, shipping group says' },
    ],
    confidenceScore: 91, status: 'VERIFIED',
    tags: ['Houthi', 'tanker', 'Gulf of Aden', 'shipping', 'anti-ship missile', 'Yemen'],
    perspective: {
      sideA: 'Houthis claim attack on "Israeli-linked vessel" as part of naval campaign',
      sideB: 'Vessel owner denies any Israeli connection; UKMTO confirms crew evacuation',
      neutral: 'Maritime distress confirmed by multiple shipping security agencies; AIS signal lost',
    },
  },
  {
    id: 'mock-007',
    createdAt: m(95),
    headline: 'Israeli airstrike targets weapons depot near Damascus airport',
    summary: 'Unconfirmed reports of Israeli airstrikes on a weapons storage facility near Damascus International Airport. Syrian state media reports "hostile targets" intercepted by Syrian air defenses. Explosions heard across Damascus suburbs.',
    locationName: 'Damascus, Syria',
    latitude: 33.5, longitude: 36.3,
    country: 'Syria', region: 'Middle East',
    severity: 'HIGH', severityColor: 'ORANGE', category: 'STRIKE',
    sources: [
      { handle: '@QalaatAlMudiq',  tier: 3, url: 'https://x.com/QalaatAlMudiq', quote: 'Multiple explosions near Damascus airport area, cause unknown' },
      { handle: '@sentdefender',   tier: 3, url: 'https://x.com/sentdefender',  quote: 'IAF strike reported near Damascus, SANA citing air defenses active' },
      { handle: '@AlMonitor',      tier: 2, url: 'https://www.al-monitor.com',   quote: 'Syria reports interception of Israeli missiles near Damascus' },
    ],
    confidenceScore: 62, status: 'PROBABLE',
    tags: ['IDF', 'IAF', 'Syria', 'Damascus', 'airstrike', 'Hezbollah', 'weapons'],
    perspective: {
      sideA: 'Syria/Iran: air defenses successfully countered hostile targets; damage minimal',
      sideB: 'Israel has not commented (standard practice for Syria strikes)',
      neutral: 'Explosions confirmed by local residents; extent of damage unverified',
    },
  },
  {
    id: 'mock-008',
    createdAt: m(118),
    headline: 'IAEA confirms Iran has 60% enriched uranium stockpile of 142kg',
    summary: 'IAEA quarterly report reveals Iran has accumulated 142.1 kg of uranium enriched to 60%, near weapons-grade level. The agency notes Iran continues to limit inspector access to centrifuge manufacturing sites.',
    locationName: 'Natanz, Iran',
    latitude: 33.7, longitude: 51.7,
    country: 'Iran', region: 'Middle East',
    severity: 'MEDIUM', severityColor: 'YELLOW', category: 'INTELLIGENCE',
    sources: [
      { handle: '@ianbremmer',     tier: 2, url: 'https://x.com/ianbremmer',   quote: 'IAEA: Iran 60% enriched uranium stockpile now at 142.1kg' },
      { handle: '@IranIntl',       tier: 2, url: 'https://www.iranintl.com',   quote: 'UN nuclear watchdog: Iran\'s 60% HEU stockpile increases by 20kg' },
      { handle: '@Guardian',       tier: 1, url: 'https://www.theguardian.com',quote: 'Iran nuclear stockpile grows, IAEA report finds' },
      { handle: '@Reuters',        tier: 1, url: 'https://www.reuters.com',    quote: 'Iran\'s enriched uranium stockpile grows, IAEA says in quarterly report' },
    ],
    confidenceScore: 99, status: 'VERIFIED',
    tags: ['Iran', 'IAEA', 'nuclear', 'uranium', 'enrichment', 'Natanz'],
    perspective: {
      sideA: 'Iran: enrichment for civilian energy purposes only; no intent to weaponize',
      sideB: 'Israel/US: stockpile approaching threshold for nuclear weapon breakout capability',
      neutral: 'IAEA official quarterly report, independently verified; 142.1kg confirmed figure',
    },
  },
]
